### ISSUE TITLE
Helm install of aleph charts timing out

### ISSUE THREAD

**Issue by winsomeglint** [alephdata/aleph-helm-charts#1]
Hey, there. Followed the install guide using `kind` for a local install. I'm on OSX. Everything works fine until actually installing the aleph charts—I went with the local files rather than the package. The job loads in `kubectl`, but then it hangs. No events appear in `kubectl describe aleph-upgrade` either. It seems like the job never really starts and so never clears, and `helm install` terminates with the error messages `Error: failed pre-install: timed out waiting for the condition`. 

Kind version 0.9.0
Helm version 3.3.4

Thanks for any help you can provide!

**Comment by winsomeglint** [comment]
Looks like the only pre-install hook is in `charts/aleph/charts/api/templates/upgrade.yaml`. Running `helm install --no-hooks` succeeds, but not sure if this is kosher.

**Comment by sunu** [comment]
Hey @mudsill, the preinstall hook runs the database migrations and creates elasticsearch indexes. So it does take some time to run. The default timeout is 10 minutes. But if it's not working, please try increasing the timeout a bit in the Makefile command: https://github.com/alephdata/aleph-helm-charts/blob/00d2d2dfda3e5a4f236fd3ad3e2ab0bec0e6cf45/examples/kind/Makefile#L62

If you don't run the hook, you'll have to run `aleph upgrade` manually in a shell to run the migrations and to create the search indices.

Re: `aleph-upgrade` job not starting, can you make sure you're checking in the right namespace? Also, the job needs elasticsearch and postgres services to be up and running. They'll take some time to start up during installation.

Also, please read our [support policy](https://github.com/alephdata/aleph/blob/main/SUPPORT.md) in case you have more queries
