### ISSUE TITLE
Non-S3 Config

### ISSUE THREAD

**Issue by winsomeglint** [alephdata/aleph-helm-charts#2]
I read the support policy but don't think this falls under support. Just thought I could supply a configuration using local storage rather than S3. I'd be happy to write a pull request with appropriate settings if that were something that seemed useful.

**Comment by mudsill** [comment]
`/data` is mounted as an `emptyDir`.

**Comment by mudsill** [comment]
I'm guessing that a `PersistentVolumeClaim` needs to be written for `aleph-api`, `aleph-worker`, and `aleph-file`, and `aleph-convert-document`.

**Comment by sunu** [comment]
Hi @mudsill, that would definitely be useful and welcome! An alternative is to use MinIO as a S3 replacement.

**Comment by mattcg** [comment]
@mudsill our experience with this is:

- if running Aleph on k8s you don't want to store 1TB+ of data in a container image
- you can run Minio in a VM (not on k8s) and give it direct disk access
- to Aleph, Minio looks just like S3

**Comment by sunu** [comment]
Closing this since we have self-hosted storage support through Minio.
