### ISSUE TITLE
Use a helm repository to publish the charts

### ISSUE THREAD

**Issue by sunu** [alephdata/aleph-helm-charts#5]
Possible candidates are:
- Artifacthub (https://artifacthub.io/)
- Github Package Registry (https://github.com/github/roadmap/issues/120)

**Comment by pudo** [comment]
ArtifactHub seems really cool, and we can always migrate over to GHCR when they provide helm support next year.

**Comment by sunu** [comment]
I looked a bit more into Artifacthub. It only supports indexing existing helm repositories. It can't act as a helm repository on it's own.

That means we need to set up our own repository either through GitHub Pages or may be GCS as described in https://helm.sh/docs/topics/chart_repository/

**Comment by sunu** [comment]
Fixed in https://github.com/alephdata/aleph/pull/1557. Helm chart repo is at https://aleph-helm-charts.storage.googleapis.com/
