### ISSUE TITLE
maxReplicas resetting to 60 after every helm chart upgrade

### ISSUE THREAD

**Issue by mattcg** [alephdata/aleph-helm-charts#7]
Hard-coded values in values.yaml are causing a reset of everything in our values YAML. This happens during every upgrade. Each time there's a new helm chart released our server tries to spin up 60 replicas.

**Comment by sunu** [comment]
That sounds weird. User supplied values should be able to override the default hard-coded values. Can I know how you do upgrades?

**Comment by ghost** [comment]
Hey @sunu we're using Rancher. It works for other variables, at least in "global" part:

global:
  amazon: true
...
ingest-file:
  env:
    INGESTORS_CONVERT_DOCUMENT_URL: 'http://aleph-convert-document.aleph.svc.cluster.local:3000/convert'
  hpa.maxReplicas: 7

**Comment by sunu** [comment]
Hey @dmitry-rancher, silly question but are you setting `hpa.maxReplicas: 7` or
```
hpa:
  maxReplicas: 7
```
First one won't be parsed and merged the way you want but second one should be.

**Comment by sunu** [comment]
You can check by running the helm command with `--dry-run` flag of course

**Comment by ghost** [comment]
Yup, that was it. Thanks for the hint! 👍

**Comment by mattcg** [comment]
Thank you, sunu!
